-- Initial migration
-- This will be generated by drizzle-kit, but creating a placeholder

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);

CREATE TABLE IF NOT EXISTS orgs (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS org_members (
  org_id TEXT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'admin',
  permissions JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(org_id, user_id)
);

CREATE TABLE IF NOT EXISTS invitations (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  role TEXT NOT NULL,
  token TEXT NOT NULL UNIQUE,
  invited_by TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMP NOT NULL,
  accepted_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_invitations_token ON invitations(token);
CREATE INDEX IF NOT EXISTS idx_invitations_org_id ON invitations(org_id);

CREATE TABLE IF NOT EXISTS sites (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  public_site_id TEXT NOT NULL UNIQUE,
  public_write_key TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS path_rules (
  id TEXT PRIMARY KEY,
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE UNIQUE,
  rules_json JSONB NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS event_defs (
  id TEXT PRIMARY KEY,
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  event_name TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  props_allowlist JSONB,
  value_rule JSONB,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(site_id, event_name)
);

CREATE TABLE IF NOT EXISTS events_raw (
  id BIGSERIAL PRIMARY KEY,
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  ts TIMESTAMP NOT NULL,
  vid TEXT NOT NULL,
  sid TEXT NOT NULL,
  path TEXT NOT NULL,
  event_type TEXT NOT NULL,
  event_name TEXT,
  ref_domain TEXT,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  utm_content TEXT,
  utm_term TEXT,
  country CHAR(2),
  device_category TEXT,
  os TEXT,
  sw INTEGER,
  sh INTEGER,
  dpr NUMERIC(3,2),
  browser_name TEXT,
  browser_version TEXT,
  browser_engine TEXT,
  language TEXT,
  connection_type TEXT,
  scroll_depth INTEGER,
  error_type TEXT,
  error_message TEXT,
  search_term TEXT,
  lcp INTEGER,
  fid INTEGER,
  cls NUMERIC(5,3),
  ttfb INTEGER,
  fcp INTEGER,
  custom_dimensions JSONB,
  props JSONB,
  value NUMERIC(15,2),
  currency TEXT
);

CREATE INDEX IF NOT EXISTS idx_events_raw_site_ts ON events_raw(site_id, ts DESC);
CREATE INDEX IF NOT EXISTS idx_events_raw_site_event_ts ON events_raw(site_id, event_name, ts DESC);
CREATE INDEX IF NOT EXISTS idx_events_raw_site_sid_ts ON events_raw(site_id, sid, ts ASC);
CREATE INDEX IF NOT EXISTS idx_events_raw_site_path_ts ON events_raw(site_id, path, ts DESC);

CREATE TABLE IF NOT EXISTS rollup_minute (
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  minute_ts TIMESTAMP NOT NULL,
  path TEXT NOT NULL,
  event_key TEXT NOT NULL,
  country CHAR(2),
  device_category TEXT,
  os TEXT,
  ref_domain TEXT,
  utm_source TEXT,
  utm_medium TEXT,
  utm_campaign TEXT,
  count INTEGER NOT NULL DEFAULT 0,
  value_sum NUMERIC(15,2),
  PRIMARY KEY (site_id, minute_ts, path, event_key, country, device_category, os, ref_domain, utm_source, utm_medium, utm_campaign)
);

CREATE TABLE IF NOT EXISTS ingest_stats (
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  minute_ts TIMESTAMP NOT NULL,
  accepted_count INTEGER NOT NULL DEFAULT 0,
  dropped_invalid INTEGER NOT NULL DEFAULT 0,
  dropped_pii INTEGER NOT NULL DEFAULT 0,
  dropped_rate_limited INTEGER NOT NULL DEFAULT 0,
  dropped_cardinality INTEGER NOT NULL DEFAULT 0,
  last_event_ts TIMESTAMP,
  PRIMARY KEY (site_id, minute_ts)
);

CREATE TABLE IF NOT EXISTS dim_cardinality (
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  day DATE NOT NULL,
  dimension TEXT NOT NULL,
  value_hash TEXT NOT NULL,
  UNIQUE(site_id, day, dimension, value_hash)
);

CREATE TABLE IF NOT EXISTS goals (
  id TEXT PRIMARY KEY,
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  config JSONB NOT NULL,
  description TEXT,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS segments (
  id TEXT PRIMARY KEY,
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  conditions JSONB NOT NULL,
  description TEXT,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS scheduled_reports (
  id TEXT PRIMARY KEY,
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  config JSONB NOT NULL,
  schedule JSONB NOT NULL,
  recipients JSONB NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS errors (
  id TEXT PRIMARY KEY,
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  fingerprint TEXT NOT NULL,
  type TEXT NOT NULL,
  message TEXT NOT NULL,
  url TEXT,
  first_seen TIMESTAMP NOT NULL,
  last_seen TIMESTAMP NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  resolved BOOLEAN NOT NULL DEFAULT false,
  resolved_at TIMESTAMP,
  environment TEXT,
  release TEXT,
  UNIQUE(site_id, fingerprint)
);

CREATE TABLE IF NOT EXISTS error_events (
  id BIGSERIAL PRIMARY KEY,
  error_id TEXT NOT NULL REFERENCES errors(id) ON DELETE CASCADE,
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  vid TEXT NOT NULL,
  sid TEXT NOT NULL,
  ts TIMESTAMP NOT NULL,
  path TEXT,
  user_agent TEXT,
  props JSONB
);

CREATE INDEX IF NOT EXISTS idx_error_events_error_id ON error_events(error_id);
CREATE INDEX IF NOT EXISTS idx_error_events_site_id ON error_events(site_id);

CREATE TABLE IF NOT EXISTS performance_metrics (
  id BIGSERIAL PRIMARY KEY,
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  ts TIMESTAMP NOT NULL,
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  duration INTEGER,
  status INTEGER,
  size INTEGER,
  props JSONB
);

CREATE INDEX IF NOT EXISTS idx_performance_metrics_site_ts ON performance_metrics(site_id, ts DESC);

CREATE TABLE IF NOT EXISTS form_analytics (
  id BIGSERIAL PRIMARY KEY,
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  ts TIMESTAMP NOT NULL,
  form_id TEXT NOT NULL,
  field_name TEXT,
  event_type TEXT NOT NULL,
  sid TEXT NOT NULL,
  time_spent INTEGER,
  error_count INTEGER,
  error_type TEXT,
  props JSONB
);

CREATE INDEX IF NOT EXISTS idx_form_analytics_site_ts ON form_analytics(site_id, ts DESC);
CREATE INDEX IF NOT EXISTS idx_form_analytics_form_id ON form_analytics(form_id);

CREATE TABLE IF NOT EXISTS custom_event_trackers (
  id TEXT PRIMARY KEY,
  site_id TEXT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  event_name TEXT NOT NULL,
  value NUMERIC(15,2),
  css_selector TEXT NOT NULL,
  css_classes JSONB NOT NULL,
  element_tag TEXT,
  description TEXT,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_custom_event_trackers_site_id ON custom_event_trackers(site_id);
CREATE INDEX IF NOT EXISTS idx_custom_event_trackers_enabled ON custom_event_trackers(site_id, enabled) WHERE enabled = true;

